#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase
#cleanSamples
> srun.log

find . \( -name 'nPart*' \) -exec rm {} \;
find . \( -name 'zeta*' \) -exec rm {} \;
find . \( -name 'gamma1_*' \) -exec rm {} \;

# ----------------------------------------------------------------- end-of-file
