#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="0 constant log.icoFoam o.foam pxx system"
loseCases="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 VTK"

for caseName in $keepCases
do
(
    cd $caseName || exit
    foamCleanTutorials
)
done

for caseName in $loseCases
do
    removeCase $caseName
done

#------------------------------------------------------------------------------
